import type { BusinessRule } from "./types.ts";

/**
 * Business Rule registry — seed data transcribed from the verified
 * ΤΣΙΑΝΤΗΣ AI knowledge base (Cowork plugin, files 01/03/15/16), which
 * remains the source of provenance/audit. This is the structured,
 * queryable version that the running application uses; in production
 * this table lives in the database (see prisma/schema.prisma -> BusinessRule)
 * and this file becomes the one-time seed script's data source.
 *
 * Never edit numbers here without the same confirmation trail the
 * knowledge base requires. Superseding a rule: add a new record with a
 * higher VERSION and STATUS=VERIFIED/USER_VERIFIED, and set the old
 * record's STATUS=SUPERSEDED + VALID_TO — never delete history.
 */

export const BUSINESS_RULES: BusinessRule[] = [
  {
    RULE_ID: "EUROPA_850_MONOFYLLO_CUT",
    CATEGORY: "CUTTING",
    SYSTEM: "EUROPA_850",
    TYPOLOGY: "ΜΟΝΟΦΥΛΛΟ",
    VARIABLES: ["frameW", "frameH"],
    FORMULA: "φύλλο = κάσα − 47 · τζάμι = φύλλο − 118",
    SOURCE: "knowledge/01_CUTTING_RULES.md, knowledge/09_CONFIRMED_EXAMPLES.md #1",
    STATUS: "USER_VERIFIED",
    VERSION: 1,
    VALID_FROM: "2026-09-01",
    VALID_TO: null,
    VERIFICATION_STATE: "CONFIRMED από Φίλιππο, διπλός έλεγχος με παράδειγμα 1200x1400",
    UPDATED_BY: "PHILIPPOS",
    UPDATED_AT: "2026-09-10T00:00:00Z",
  },
  {
    RULE_ID: "EUROPA_8500_MONOFYLLO_CUT",
    CATEGORY: "CUTTING",
    SYSTEM: "EUROPA_8500",
    TYPOLOGY: "ΜΟΝΟΦΥΛΛΟ",
    VARIABLES: ["frameW", "frameH"],
    FORMULA: "φύλλο = κάσα − 47 · τζάμι = φύλλο − 118 (ίδιο με 850, διαφέρει μόνο πάχος τζαμιού)",
    SOURCE: "knowledge/01_CUTTING_RULES.md",
    STATUS: "USER_VERIFIED",
    VERSION: 1,
    VALID_FROM: "2026-09-01",
    VALID_TO: null,
    VERIFICATION_STATE: "CONFIRMED από Φίλιππο",
    UPDATED_BY: "PHILIPPOS",
    UPDATED_AT: "2026-09-10T00:00:00Z",
  },
  {
    RULE_ID: "EUROPA_850_8500_ROLLER_CUT",
    CATEGORY: "CUTTING",
    SYSTEM: "EUROPA_850_8500",
    TYPOLOGY: "ΜΟΝΟΦΥΛΛΟ_ΜΕ_ΡΟΛΟ",
    VARIABLES: ["openingW", "openingH", "heightMode", "boxHeight"],
    FORMULA:
      "κάσα.πλάτος = άνοιγμα.πλάτος + 3 · κάσα.ύψος = ΣΥΝ_ΚΟΥΤΙ ? άνοιγμα.ύψος : (ΟΛΙΚΟ ? άνοιγμα.ύψος − κουτί : —) · μετά τρέχει κανονικά −47/−118",
    SOURCE: "knowledge/01_CUTTING_RULES.md, knowledge/09_CONFIRMED_EXAMPLES.md #2",
    STATUS: "USER_VERIFIED",
    VERSION: 1,
    VALID_FROM: "2026-09-01",
    VALID_TO: null,
    VERIFICATION_STATE: "CONFIRMED, διασταυρωμένο με ΚΟΠΕΣ ΜΟΝΟΦΥΛΛΑ",
    UPDATED_BY: "PHILIPPOS",
    UPDATED_AT: "2026-09-10T00:00:00Z",
  },
  {
    RULE_ID: "KARE_ROLLOU_CUT",
    CATEGORY: "CUTTING",
    SYSTEM: "EUROPA_850_8500",
    TYPOLOGY: "ΚΑΡΕ_ΡΟΛΟΥ",
    VARIABLES: ["frameW", "frameH"],
    FORMULA: "οδηγοί (2τεμ) = κάσα.ύψος − 3 · κάτω (1τεμ) = κάσα.πλάτος − 46",
    SOURCE: "knowledge/01_CUTTING_RULES.md, knowledge/09_CONFIRMED_EXAMPLES.md #5",
    STATUS: "USER_VERIFIED",
    VERSION: 1,
    VALID_FROM: "2026-09-01",
    VALID_TO: null,
    VERIFICATION_STATE: "CONFIRMED",
    UPDATED_BY: "PHILIPPOS",
    UPDATED_AT: "2026-09-10T00:00:00Z",
  },
  {
    RULE_ID: "GLASS_850_871_8500",
    CATEGORY: "GLASS",
    SYSTEM: "EUROPA_850",
    TYPOLOGY: "ΦΥΛΛΟ_871_ΠΗΧΑΚΙ_8500",
    VARIABLES: ["leafW", "leafH"],
    FORMULA: "τζάμι = φύλλο − 118 · μέγιστο πάχος 18mm · σύνθεση 4-10-4",
    SOURCE: "knowledge/03_GLASS_RULES.md",
    STATUS: "USER_VERIFIED",
    VERSION: 2,
    VALID_FROM: "2026-09-01",
    VALID_TO: null,
    VERIFICATION_STATE: "CONFIRMED — διορθώθηκε ρητά από 24mm σε 18mm",
    UPDATED_BY: "PHILIPPOS",
    UPDATED_AT: "2026-09-10T00:00:00Z",
  },
  {
    RULE_ID: "GLASS_8500_8550_8500",
    CATEGORY: "GLASS",
    SYSTEM: "EUROPA_8500",
    TYPOLOGY: "ΦΥΛΛΟ_8550_ΠΗΧΑΚΙ_8500",
    VARIABLES: ["leafW", "leafH"],
    FORMULA: "τζάμι = φύλλο − 118 · μέγιστο πάχος 24mm · σύνθεση 4-16-4",
    SOURCE: "knowledge/03_GLASS_RULES.md",
    STATUS: "USER_VERIFIED",
    VERSION: 1,
    VALID_FROM: "2026-09-01",
    VALID_TO: null,
    VERIFICATION_STATE: "CONFIRMED",
    UPDATED_BY: "PHILIPPOS",
    UPDATED_AT: "2026-09-10T00:00:00Z",
  },
  {
    RULE_ID: "PVC_STATHERO_CUT",
    CATEGORY: "CUTTING",
    SYSTEM: "PVC",
    TYPOLOGY: "ΣΤΑΘΕΡΟ",
    VARIABLES: ["W", "H"],
    FORMULA: "κάσα=W+6 x H+6 · σίδερο κάσας=W-120 x H-120 · τζάμι=W-98 x H-98",
    SOURCE: "knowledge/16_PVC_CUTS_COSTING.md §2, knowledge/17_PVC_RAW_SOURCE_APPENDIX.md",
    STATUS: "USER_VERIFIED",
    VERSION: 1,
    VALID_FROM: "2026-09-10",
    VALID_TO: null,
    VERIFICATION_STATE: "USER VERIFIED — CLAUDE_PVC_CUTS_COSTING_MASTER_v2_VERIFIED.md",
    UPDATED_BY: "PHILIPPOS",
    UPDATED_AT: "2026-09-10T00:00:00Z",
  },
  {
    RULE_ID: "PVC_MONOFYLLO_CUT",
    CATEGORY: "CUTTING",
    SYSTEM: "PVC",
    TYPOLOGY: "ΜΟΝΟΦΥΛΛΟ",
    VARIABLES: ["W", "H"],
    FORMULA:
      "κάσα=W+6 x H+6 · φύλλο=W-66 x H-66 · σίδερο κάσας=W-120 x H-120 (2τεμ) · σίδερο φύλλου=W-190 x H-190 (2τεμ) · τζάμι=W-202 x H-202 (ενεργός κανόνας, βλ. PVC_GLASS_RULE) · πιχάκι=W-192 x H-192",
    SOURCE: "knowledge/16_PVC_CUTS_COSTING.md §3",
    STATUS: "USER_VERIFIED",
    VERSION: 1,
    VALID_FROM: "2026-09-10",
    VALID_TO: null,
    VERIFICATION_STATE: "USER VERIFIED",
    UPDATED_BY: "PHILIPPOS",
    UPDATED_AT: "2026-09-10T00:00:00Z",
  },
  {
    RULE_ID: "PVC_DIFYLLO_CUT",
    CATEGORY: "CUTTING",
    SYSTEM: "PVC",
    TYPOLOGY: "ΔΙΦΥΛΛΟ",
    VARIABLES: ["W", "H"],
    FORMULA:
      "κάσα=W+6 x H+6 · κάθε φύλλο=(W/2-34) x (H-66) · κάθετο στοιχείο(ΜΠΙΝΙ)=H-153 [PENDING ονομασία] · σίδερο κάσας=W-120 x H-120 (2τεμ) · σίδερο φύλλου=(W/2-160) x (H-190) (4τεμ) · τζάμι ανά φύλλο=(W/2-170) x (H-202) (2τεμ) · πιχάκι ανά φύλλο=(W/2-160) x (H-192)",
    SOURCE: "knowledge/16_PVC_CUTS_COSTING.md §4",
    STATUS: "USER_VERIFIED",
    VERSION: 1,
    VALID_FROM: "2026-09-10",
    VALID_TO: null,
    VERIFICATION_STATE:
      "USER VERIFIED, εκτός από τη σημασία του H-153 (CRITICAL_CONFLICT_003, PENDING)",
    UPDATED_BY: "PHILIPPOS",
    UPDATED_AT: "2026-09-10T00:00:00Z",
  },
  {
    RULE_ID: "PVC_GLASS_RULE",
    CATEGORY: "GLASS",
    SYSTEM: "PVC",
    TYPOLOGY: "ΜΟΝΟΦΥΛΛΟ_ΔΙΦΥΛΛΟ",
    VARIABLES: ["leafW", "leafH"],
    FORMULA: "τζάμι = φύλλο − 136 (και στους δύο άξονες)",
    SOURCE: "knowledge/16_PVC_CUTS_COSTING.md §5",
    STATUS: "USER_VERIFIED",
    VERSION: 2,
    VALID_FROM: "2026-09-10",
    VALID_TO: null,
    VERIFICATION_STATE:
      "CONFIRMED 10/09 — αντικατέστησε την παλιά φόρμουλα κοστολόγησης (φύλλο−128), η οποία είναι SUPERSEDED",
    UPDATED_BY: "PHILIPPOS",
    UPDATED_AT: "2026-09-10T00:00:00Z",
  },
  {
    RULE_ID: "PVC_GLASS_RULE_COSTING_OLD",
    CATEGORY: "GLASS",
    SYSTEM: "PVC",
    TYPOLOGY: "ΜΟΝΟΦΥΛΛΟ_ΔΙΦΥΛΛΟ",
    VARIABLES: ["leafW", "leafH"],
    FORMULA: "τζάμι = φύλλο − 128 (SUPERSEDED, ΜΗΝ χρησιμοποιηθεί)",
    SOURCE: "ΚΟΣΤΟΛΟΓΗΣΗ ΠΙΒΙΣΙ.xlsm (πρωτότυπο, πριν τη διόρθωση 10/09)",
    STATUS: "SUPERSEDED",
    VERSION: 1,
    VALID_FROM: "2020-01-01",
    VALID_TO: "2026-09-10",
    VERIFICATION_STATE: "ΑΝΤΙΚΑΤΑΣΤΑΘΗΚΕ από PVC_GLASS_RULE v2 στις 10/09",
    UPDATED_BY: "PHILIPPOS",
    UPDATED_AT: "2026-09-10T00:00:00Z",
  },
  {
    RULE_ID: "ROLLER_CATALOG_DISCOUNT",
    CATEGORY: "DISCOUNT",
    SYSTEM: "GENERAL",
    TYPOLOGY: "N/A",
    VARIABLES: ["catalogPrice"],
    FORMULA: "NET_PURCHASE_PRICE = CATALOG_PRICE × (1 − ROLLER_CATALOG_DISCOUNT_PERCENT / 100)",
    SOURCE: "knowledge/15_PRICING_VARIABLES.md",
    STATUS: "USER_VERIFIED",
    VERSION: 1,
    VALID_FROM: "2026-09-10",
    VALID_TO: null,
    VERIFICATION_STATE:
      "CONFIRMED 10/09 — η τιμή 6% είναι ΜΕΤΑΒΛΗΤΗ, κεντρικό σημείο αλλαγής pricing-variables.ts / πίνακας PricingVariable",
    UPDATED_BY: "PHILIPPOS",
    UPDATED_AT: "2026-09-10T00:00:00Z",
  },
];

export function getRule(ruleId: string): BusinessRule {
  const rule = BUSINESS_RULES.find((r) => r.RULE_ID === ruleId);
  if (!rule) {
    throw new Error(`Άγνωστος κανόνας: ${ruleId}. Δεν επινοούμε κανόνες — πρέπει να καταχωρηθεί πρώτα.`);
  }
  return rule;
}
